### ISSUE TITLE
after using AnimateInOut, FLIP will be invalid ? 

### ISSUE THREAD

**Issue by peoplesing1832** [jlkiri/react-easy-flip#26]
https://react-easy-flip-demo.now.sh/in-out

**Comment by jlkiri** [comment]
I'd say it may be possible but `AnimateInOut` is actually in a pretty experimental state and I would not hope to make BOTH work. In fact I'm working on the next version in which I remove `AnimateInOut`. This is because I wrote another hook which is going to be independent from `react-easy-flip`: https://github.com/jlkiri/use-animate-presence

In fact there is a working demo of these two libs together:

https://codesandbox.io/s/animate-presence-multiple-2-o804h?fontsize=14&hidenavigation=1&theme=dark
